```{r}
#Websites Referenced for this work:
#https://stackoverflow.com/questions/71461144/is-there-a-way-to-add-a-column-of-percentage-of-total-count-into-r
#https://stackoverflow.com/questions/21878974/wrap-long-axis-labels-via-labeller-label-wrap-in-ggplot2
#http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels
#https://www.tutorialspoint.com/how-to-set-the-x-axis-labels-in-histogram-using-ggplot2-at-the-center-in-r
#http://www.sthda.com/english/wiki/ggplot2-add-straight-lines-to-a-plot-horizontal-vertical-and-regression-lines
```


```{r}
#first, install and load required libraries
#using function provided by Professor Krudys.

#specify the packages needed
packages=c("tidyverse", "readxl","ggplot2","dplyr","stats")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

#verify they are loaded
search()
```

```{r}
#download Employment Growth File and Create a Data Frame

#URLs of datasets to be used:
employmentGrowth <- "https://datacatalogfiles.worldbank.org/ddh-published/0038045/DR0046261/public_use-industry-employment-growth.xlsx?versionId=2023-01-19T09:28:51.4382607Z"

#download this file from the web into a temporary Excel file
download.file(employmentGrowth, "tmpExcelFileEmploymentGrowth.xlsx", quiet=TRUE, mode="wb")

#read the sheet into a new dataframe
EmploymentGrowthDF <- data.frame(read_excel("tmpExcelFileEmploymentGrowth.xlsx", sheet = "Growth from Industry Transition"))
```


```{r}
#check for NA's in the dataset
colSums(is.na(EmploymentGrowthDF))
```

```{r}
#Update Employment Growth with an average for each observation
#calculate the average of all growth measures and capture in a new column
EmploymentGrowthDF <- EmploymentGrowthDF %>% mutate(cumulative_growth_rate=((growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018+growth_rate_2019)/5))
head(EmploymentGrowthDF)
```

```{r}
#download Skills Needs File and Create a Data Frame

#URLs of datasets to be used:
skillsNeeds <- "https://datacatalogfiles.worldbank.org/ddh-published/0038027/DR0046191/public_use-industry-skills-needs.xlsx?versionId=2023-01-19T03:44:21.4528001Z"

#download this file from the web into a temporary Excel file
download.file(skillsNeeds, "tmpExcelFileSkillNeeds.xlsx", quiet=TRUE, mode="wb")

#read the sheet into a new dataframe
skillsNeedsDF <- data.frame(read_excel("tmpExcelFileSkillNeeds.xlsx", sheet = "Industry Skills Needs"))
```

```{r}
#download the Consolidated Migration Info File and Create 3 Data Frames
migrationInfo <- "https://datacatalogfiles.worldbank.org/ddh-published/0038044/DR0046256/public_use-talent-migration.xlsx?versionId=2024-02-13T16:57:39.2869535Z"

#download this file from the web into a temporary Excel file
download.file(migrationInfo, "tmpExcelFileMigration.xlsx", quiet=TRUE, mode="wb")

#read the sheet into a new dataframe
countryMigrationDF <- data.frame(read_excel("tmpExcelFileMigration.xlsx", sheet = "Country Migration"))
#read the sheet into a new dataframe
industryMigrationDF <- data.frame(read_excel("tmpExcelFileMigration.xlsx", sheet = "Industry Migration"))
#read the sheet into a new dataframe
skillMigrationDF <- data.frame(read_excel("tmpExcelFileMigration.xlsx", sheet = "Skill Migration"))
```

```{r}
#download Skills Penetration File and Create a Data Frame

#URLs of datasets to be used:
skillsPenetration <- "https://datacatalogfiles.worldbank.org/ddh-published/0038027/DR0046192/public_use-skill-penetration.xlsx?versionId=2023-01-19T03:44:28.0600027Z"

#download this file from the web into a temporary Excel file
download.file(skillsPenetration, "tmpExcelFileSkillPenetration.xlsx", quiet=TRUE, mode="wb")

#read the sheet into a new dataframe
skillsPenetrationDF <- data.frame(read_excel("tmpExcelFileSkillPenetration.xlsx", sheet = "Skill Penetration"))
```


```{r}
#Break down employment growth by Region

#East Asia & Pacific Data
growthEAP.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "East Asia & Pacific")

#Europe & Central Asia Data
growthECA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Europe & Central Asia")

#Latin America & Caribbean Data
growthLAC.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Latin America & Caribbean")

#Middle East & North Africa Data
growthMENA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Middle East & North Africa")

#North America Data
growthNA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "North America")

#South Asia Data
growthSA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "South Asia")

#Sub-Saharan Africa Data
growthSSA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Sub-Saharan Africa")
```


```{r}
#build regional data frames that contain average growth rate by isic_section
EAP_EmployeeGrowth.df <- growthEAP.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
ECA_EmployeeGrowth.df <- growthECA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
LAC_EmployeeGrowth.df <- growthLAC.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
MENA_EmployeeGrowth.df <- growthMENA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
NA_EmployeeGrowth.df <- growthNA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
SA_EmployeeGrowth.df <- growthSA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
SSA_EmployeeGrowth.df <- growthSSA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))

head(EAP_EmployeeGrowth.df)
```

```{r}
#merge the isic_section_mean back into the regional data frames

EAP_EmployeeData <- merge(growthEAP.df, EAP_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
EAP_EmployeeData$growth_rate_variance <- EAP_EmployeeData$cumulative_growth_rate - EAP_EmployeeData$isic_section_mean_rate

ECA_EmployeeData <- merge(growthECA.df, ECA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
ECA_EmployeeData$growth_rate_variance <- ECA_EmployeeData$cumulative_growth_rate - ECA_EmployeeData$isic_section_mean_rate

LAC_EmployeeData <- merge(growthLAC.df, LAC_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
LAC_EmployeeData$growth_rate_variance <- LAC_EmployeeData$cumulative_growth_rate - LAC_EmployeeData$isic_section_mean_rate

MENA_EmployeeData <- merge(growthMENA.df, MENA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
MENA_EmployeeData$growth_rate_variance <- MENA_EmployeeData$cumulative_growth_rate - MENA_EmployeeData$isic_section_mean_rate

NA_EmployeeData <- merge(growthNA.df, NA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
NA_EmployeeData$growth_rate_variance <- NA_EmployeeData$cumulative_growth_rate - NA_EmployeeData$isic_section_mean_rate

SA_EmployeeData <- merge(growthSA.df, SA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
SA_EmployeeData$growth_rate_variance <- SA_EmployeeData$cumulative_growth_rate - SA_EmployeeData$isic_section_mean_rate

SSA_EmployeeData <- merge(growthSSA.df, SSA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
SSA_EmployeeData$growth_rate_variance <- SSA_EmployeeData$cumulative_growth_rate - SSA_EmployeeData$isic_section_mean_rate
```

#visualize Average Industry Growth for each Region
```{r}
#convert to %
EAP_EmployeeGrowth.df$isic_section_mean_rate <- EAP_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(EAP_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("East Asia & Pacific: Average Employement Growth by Industry Sector") + 
  labs(x="ISIC Industry Category") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(0, 2.75),breaks=seq(0,2.75,.25))

#convert to %
ECA_EmployeeGrowth.df$isic_section_mean_rate <- ECA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(ECA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("Europe & Central Asia: Average Employment Growth by Industry Sector") + 
  labs(x="ISIC Industry Category")  + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(0, 1.5), breaks=seq(0,1.5,.25))

#convert to %
LAC_EmployeeGrowth.df$isic_section_mean_rate <- LAC_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(LAC_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("Latin America & Caribbean: Average Employment Growth by Industry Sector") + 
  labs(x="ISIC Industry Category")  + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-1.75, 0), breaks=seq(-1.75,0,.25))

#convert to %
MENA_EmployeeGrowth.df$isic_section_mean_rate <- MENA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(MENA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("Middle East & North Africa: Average Employment Growth by Industry Sector") + 
  labs(x="ISIC Industry Category")  + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-1.75, 1), breaks=seq(-1.75,1,.25))

#convert to %
NA_EmployeeGrowth.df$isic_section_mean_rate <- NA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(NA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("North America: Average Employment Growth by Industry Sector") + labs(x="ISIC Industry Category") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(0, 2.75), breaks=seq(0,2.75,.25))

#convert to %
SA_EmployeeGrowth.df$isic_section_mean_rate <- SA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(SA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("South Asia: Average Employment Growth by Industry Sector") + 
  labs(x="ISIC Industry Category")  + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-2.0, 0), breaks=seq(-2.0,0,.25))

#visualize the trending
ggplot(SSA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  ggtitle("Sub-Saharan Africa: Average Employment Growth by Industry Sector") + 
  labs(x="ISIC Industry Category")  + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-.015, 0.015), breaks=seq(-.015,0.015,.005))
```

```{r}
#East Asia & Pacific: Investigate factors driving "Financial and Insurance activities"

#select only the industry category with the largest trending
EAP_Largest_Average <- EAP_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
EAP_Largest_Average$growth_rate_variance <- EAP_Largest_Average$growth_rate_variance*100
EAP_Largest_Average$cumulative_growth_rate <- EAP_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(EAP_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  labs(x="Average Employment Growth Variance from isic_section_mean") + 
  scale_x_continuous(breaks=-13:18) + geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "East Asia & Pacific", subtitle = "Employment Growth Rate Variance of Financial and Insurace Activities ISIC Category") 

#visualize growth by industry section - bar chart
ggplot(EAP_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-25, 70), breaks=seq(-25,70,5)) + 
  labs(title = "East Asia & Pacific", subtitle = "Average Employment Growth Spread for Financial and Insurace Industry Sectors", x="Financial and Insurace Industry Sectors") 

#visualize growth by industry section - box plot
ggplot(EAP_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-10, 20), breaks=seq(-10,20,2)) + 
  labs(title = "East Asia & Pacific", subtitle = "Employment Growth Rate IQR for Financial and Insurace Industry Sectors", x="Financial and Insurace Industry Sectors")

```
```{r}
#Europe & Central Asia: Investigate factors driving "Financial and Insurance activities"

#select only the industry category with the largest trending
ECA_Largest_Average <- ECA_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
ECA_Largest_Average$growth_rate_variance <- ECA_Largest_Average$growth_rate_variance*100
ECA_Largest_Average$cumulative_growth_rate <- ECA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(ECA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-13:24) + geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Count", limits=c(0, 140), breaks=seq(0,140,10))  + 
  labs(title = "Europe & Central Asia", subtitle = "Employment Growth Rate Variance for Financial and Insurace Activities ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(ECA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-60, 150), breaks=seq(-60,150,10)) + 
  labs(title = "Europe & Central Asia", subtitle = "Average Employment Growth Spread of Financial and Insurace Activities Sectors", x="Financial and Insurace Industry Sectors")

#visualize growth by industry section - box plot
ggplot(ECA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-10, 25), breaks=seq(-10,25,10)) + 
  labs(title = "Europe & Central Asia", subtitle = "Employment Growth Rate IQR of Financial and Insurace Industry Sectors", x="Financial and Insurace Industry Sectors")
```
```{r}
#Latin America & Caribbean: Investigate factors driving "Information and Communication"

#select only the industry category with the largest trending
LAC_Largest_Average <- LAC_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
LAC_Largest_Average$growth_rate_variance <- LAC_Largest_Average$growth_rate_variance*100
LAC_Largest_Average$cumulative_growth_rate <- LAC_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(LAC_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-24:13)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "Latin America & Caribbean", subtitle = "Employment Growth Rate Variance of Information and Communication ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-55, 35), breaks=seq(-55,35,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Latin America & Caribbean", subtitle = "Average Employment Growth Spread of Information and Communication Sectors", x="Information and Communication Sectors")

#visualize growth by industry section - box plot
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-10, 12), breaks=seq(-10,12,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Latin America & Caribbean", subtitle = "Employment Growth Rate IQR of Information and Communication Sectors", x="Information and Communication Sectors")
```

```{r}
#Middle East & North Africa: Investigate factors driving "Information and Communication"

#select only the industry category with the largest trending
MENA_Largest_Average <- MENA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
MENA_Largest_Average$growth_rate_variance <- MENA_Largest_Average$growth_rate_variance*100
MENA_Largest_Average$cumulative_growth_rate <- MENA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(MENA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:30)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "Middle East & North Africa", subtitle = "Employment Growth Rate Variance of Information and Communication ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(MENA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-80, 60), breaks=seq(-80,60,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Middle East & North Africa", subtitle = "Average Employment Growth Spread of Information and Communication Sectors", x="Information and Communication Sectors")

#visualize growth by industry section - box plot
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-10, 12), breaks=seq(-10,12,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Middle East & North Africa", subtitle = "Employment Growth Rate IQR of Information and Communication Sectors", x="Information and Communication Sectors")
```

```{r}
#North America: Investigate factors driving "Financial and Insurance activities"

#select only the industry category with the largest trending
NA_Largest_Average <- NA_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
NA_Largest_Average$growth_rate_variance <- NA_Largest_Average$growth_rate_variance*100
NA_Largest_Average$cumulative_growth_rate <- NA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(NA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=1) + 
  scale_x_continuous(breaks=-20:30)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 6), breaks=seq(0,6,2)) + 
  labs(title = "North America", subtitle = "Employment Growth Rate Variance of Financial and insurance activities ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(NA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-1, 20), breaks=seq(-1,20,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "North America", subtitle = "Average Employment Growth Spread of Financial and Insurance Activities Sectors", x="Financial and Insurance Activities Sectors")

#visualize growth by industry section - box plot
ggplot(NA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(0, 10), breaks=seq(0,10,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "North America", subtitle = "Employment Growth Rate IQR of Financial and Insurance Activities Sectors", x="Financial and Insurance Activities Sectors")
```

```{r}
#South Asia: Investigate factors driving "Information and Communication"

#select only the industry category with the largest trending
SA_Largest_Average <- SA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
SA_Largest_Average$growth_rate_variance <- SA_Largest_Average$growth_rate_variance*100
SA_Largest_Average$cumulative_growth_rate <- SA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(SA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:20)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 11), breaks=seq(0,11,1)) + 
  labs(title = "South Asia", subtitle = "Employment Growth Rate Variance of Information and Communication ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(SA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) +
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-28, 8), breaks=seq(-28,8,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "South Asia", subtitle = "Average Employment Growth Spread of Information and Communication Sectors", x="Information and Communication Sectors")

#visualize growth by industry section - box plot
ggplot(SA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-8, 4), breaks=seq(-8,4,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "South Asia", subtitle = "Employment Growth Rate IQR of Information and Communication Sectors", x="Information and Communication Sectors")
```

```{r}
#Sub Saharan Africa: Investigate factors driving "Information and Communication"

#select only the industry category with the largest trending
SSA_Largest_Average <- SSA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
SSA_Largest_Average$growth_rate_variance <- SSA_Largest_Average$growth_rate_variance*100
SSA_Largest_Average$cumulative_growth_rate <- SSA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(SSA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:20)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(-5, 20), breaks=seq(-5,20,10)) + 
  labs(title = "Sub Saharan Africa", subtitle = "Employment Growth Rate Variance of Information and Communication ISIC Category",x="Average Industry Growth Variance from isic_section_mean") 

#visualize growth by industry section - bar chart
ggplot(SSA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-40, 15), breaks=seq(-40,15,5)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Sub Saharan Africa", subtitle = "Average Employment Growth Spread of Information and Communication Sectors", x="Information and Communication Sectors")

#visualize growth by industry section - box plot
ggplot(SSA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-8, 8), breaks=seq(-8,8,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Sub Saharan Africa", subtitle = "Employment Growth Rate IQR of Information and Communication Sectors", x="Information and Communication Sectors")
```

