```{r}
#Websites Referenced for this work:
#https://stackoverflow.com/questions/71461144/is-there-a-way-to-add-a-column-of-percentage-of-total-count-into-r
#https://stackoverflow.com/questions/21878974/wrap-long-axis-labels-via-labeller-label-wrap-in-ggplot2
#http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels
#https://www.tutorialspoint.com/how-to-set-the-x-axis-labels-in-histogram-using-ggplot2-at-the-center-in-r
#http://www.sthda.com/english/wiki/ggplot2-add-straight-lines-to-a-plot-horizontal-vertical-and-regression-lines
```


```{r}
#first, install and load required libraries
#using function provided by Professor Krudys.

#specify the packages needed
packages=c("tidyverse", "readxl","ggplot2","dplyr","stats","caret","rpart","rpart.plot","corrplot")

#use this function to check if each package is on the local machine
#if a package is installed, it will be loaded
#if any are not, the missing package(s) will be installed and loaded
package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

#verify they are loaded
search()
```

```{r}
#download Employment Growth File and Create a Data Frame

file1 <- "tmpExcelFileEmploymentGrowth.xlsx"

#first check if the file has already been downloaded
#skip the download if it exists
if (!file.exists(file1)) {
  
#URLs of datasets to be used:
employmentGrowth <- "https://datacatalogfiles.worldbank.org/ddh-published/0038045/DR0046261/public_use-industry-employment-growth.xlsx?versionId=2023-01-19T09:28:51.4382607Z"

#download this file from the web into a temporary Excel file
download.file(employmentGrowth, "tmpExcelFileEmploymentGrowth.xlsx", quiet=TRUE, mode="wb")
} 
```


```{r}
#read the sheet into a new dataframe
EmploymentGrowthDF <- data.frame(read_excel("tmpExcelFileEmploymentGrowth.xlsx", sheet = "Growth from Industry Transition"))

#check for NA's in the dataset
colSums(is.na(EmploymentGrowthDF))
```


```{r}
  #Update Employment Growth with an average for each observation
  #calculate the average of all growth measures and capture in a new column
  #use this field to visualize growth in each region
  EmploymentGrowthDF <- EmploymentGrowthDF %>% mutate(cumulative_growth_rate=((growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018+growth_rate_2019)/5))
```


```{r}
#Break down employment growth by Region

#East Asia & Pacific Data
growthEAP.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "East Asia & Pacific")

#Europe & Central Asia Data
growthECA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Europe & Central Asia")

#Latin America & Caribbean Data
growthLAC.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Latin America & Caribbean")

#Middle East & North Africa Data
growthMENA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Middle East & North Africa")

#North America Data
growthNA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "North America")

#South Asia Data
growthSA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "South Asia")

#Sub-Saharan Africa Data
growthSSA.df <- filter(EmploymentGrowthDF, EmploymentGrowthDF$wb_region == "Sub-Saharan Africa")
```


```{r}
#build regional data frames that contain average growth rate by isic_section
EAP_EmployeeGrowth.df <- growthEAP.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
ECA_EmployeeGrowth.df <- growthECA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
LAC_EmployeeGrowth.df <- growthLAC.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
MENA_EmployeeGrowth.df <- growthMENA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
NA_EmployeeGrowth.df <- growthNA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
SA_EmployeeGrowth.df <- growthSA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
SSA_EmployeeGrowth.df <- growthSSA.df %>% group_by(isic_section_name) %>% summarize_at(vars(cumulative_growth_rate), list(isic_section_mean_rate=mean))
```


```{r}
#merge the isic_section_mean back into the regional data frames

EAP_EmployeeData <- merge(growthEAP.df, EAP_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
EAP_EmployeeData$growth_rate_variance <- EAP_EmployeeData$cumulative_growth_rate - EAP_EmployeeData$isic_section_mean_rate

ECA_EmployeeData <- merge(growthECA.df, ECA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
ECA_EmployeeData$growth_rate_variance <- ECA_EmployeeData$cumulative_growth_rate - ECA_EmployeeData$isic_section_mean_rate

LAC_EmployeeData <- merge(growthLAC.df, LAC_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
LAC_EmployeeData$growth_rate_variance <- LAC_EmployeeData$cumulative_growth_rate - LAC_EmployeeData$isic_section_mean_rate

MENA_EmployeeData <- merge(growthMENA.df, MENA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
MENA_EmployeeData$growth_rate_variance <- MENA_EmployeeData$cumulative_growth_rate - MENA_EmployeeData$isic_section_mean_rate

NA_EmployeeData <- merge(growthNA.df, NA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
NA_EmployeeData$growth_rate_variance <- NA_EmployeeData$cumulative_growth_rate - NA_EmployeeData$isic_section_mean_rate

SA_EmployeeData <- merge(growthSA.df, SA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
SA_EmployeeData$growth_rate_variance <- SA_EmployeeData$cumulative_growth_rate - SA_EmployeeData$isic_section_mean_rate

SSA_EmployeeData <- merge(growthSSA.df, SSA_EmployeeGrowth.df, by="isic_section_name")
#add the variance to the data frame
SSA_EmployeeData$growth_rate_variance <- SSA_EmployeeData$cumulative_growth_rate - SSA_EmployeeData$isic_section_mean_rate
```


```{r}
###  --- EAST ASIA & PACIFIC: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
EAP_EmployeeGrowth.df$isic_section_mean_rate <- EAP_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(EAP_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(0, 2.75),breaks=seq(0,2.75,.25)) + 
  labs(title = "East Asia & Pacific", subtitle = "Average Growth from Industry Transition by ISIC Sector", x="ISIC Industry Sector") 

#Investigate Average Industry Segments growth driving in the "Financial and Insurance activities" ISIC Sector

#select only the industry category with the largest trending
EAP_Largest_Average <- EAP_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
EAP_Largest_Average$growth_rate_variance <- EAP_Largest_Average$growth_rate_variance*100
EAP_Largest_Average$cumulative_growth_rate <- EAP_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(EAP_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-13:18) + geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "East Asia & Pacific: Financial and insurance activities", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth", x="Industry Segment Mean Variance") 

#visualize growth by industry section - bar chart
ggplot(EAP_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-25, 70), breaks=seq(-25,70,5)) + 
  labs(title = "East Asia & Pacific: Financial and insurance activities", subtitle = "Range of Growth from Industry Transition for the Financial and Insurace Industry Segments", x="Financial and Insurace Industry Segments") 

#visualize growth by industry section - box plot
ggplot(EAP_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-10, 20), breaks=seq(-10,20,2)) + 
  labs(title = "East Asia & Pacific: Financial and insurance activities", subtitle = "Growth from Industry Transition IQR for the Financial and Insurace Industry Segments", x="Financial and Insurace Industry Segments")

```

```{r}
###  --- EUROPE AND CENTRAL ASIA: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert data to %
ECA_EmployeeGrowth.df$isic_section_mean_rate <- ECA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending at the ISIC Sector Level
ggplot(ECA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(0, 1.5), breaks=seq(0,1.5,.25)) +
  labs(title = "Europe & Central Asia", subtitle = "Average Growth from Industry Transition by ISIC Sector",x="ISIC Industry Sector") 


#Investigate Average Industry Segments driving growth in the "Financial and Insurance activities" ISIC Sector

#select only the industry category with the largest trending
ECA_Largest_Average <- ECA_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
ECA_Largest_Average$growth_rate_variance <- ECA_Largest_Average$growth_rate_variance*100
ECA_Largest_Average$cumulative_growth_rate <- ECA_Largest_Average$cumulative_growth_rate*100

#3.) plot percentages
ggplot(ECA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-13:24) + geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Count", limits=c(0, 140), breaks=seq(0,140,10))  + 
  labs(title = "Europe & Central Asia: Financial and insurance activities", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth", x="Industry Segment Mean Variance") 

#4.) visualize growth by industry section - bar chart
ggplot(ECA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-60, 150), breaks=seq(-60,150,10)) + 
  labs(title = "Europe & Central Asia: Financial and insurance activities", subtitle = "Range of Growth from Industry Transition for the Financial and Insurace Industry Segments", x="Financial and Insurace Industry Segments")

#visualize growth by industry section - box plot
ggplot(ECA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-10, 25), breaks=seq(-10,25,10)) + 
  labs(title = "Europe & Central Asia: Financial and insurance activities", subtitle = "Growth from Industry Transition IQR for the Financial and Insurace Industry Segments", x="Financial and Insurace Industry Segments")
```


```{r}
###  --- LATIN AMERICA & CARRIBEAN: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
LAC_EmployeeGrowth.df$isic_section_mean_rate <- LAC_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(LAC_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-1.75, 0), breaks=seq(-1.75,0,.25)) +
  labs(title = "Latin America & Caribbean", subtitle = "Average Growth from Industry Transition by ISIC Sector", x="ISIC Industry Sector") 


#Investigate factors driving "Information and Communication"

#select only the industry category with the largest trending
LAC_Largest_Average <- LAC_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
LAC_Largest_Average$growth_rate_variance <- LAC_Largest_Average$growth_rate_variance*100
LAC_Largest_Average$cumulative_growth_rate <- LAC_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(LAC_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-24:13)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "Latin America & Caribbean: Information and communication", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth",x="Industry Segment Mean Variance") 

#visualize growth by industry section - bar chart
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-55, 35), breaks=seq(-55,35,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Latin America & Caribbean: Information and communication", subtitle = "Range of Growth from Industry Transition for the Information and communication Industry Segments", x="Information and Communication Industry Segments")

#visualize growth by industry section - box plot
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-10, 12), breaks=seq(-10,12,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Latin America & Caribbean: Information and communication", subtitle = "Growth from Industry Transition IQR for the Information and communication Industry Segments", x="Information and Communication Industry Segments")
```


```{r}
###  --- MIDDLE EAST & NORTH AFRICA: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
MENA_EmployeeGrowth.df$isic_section_mean_rate <- MENA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(MENA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-1.75, 1), breaks=seq(-1.75,1,.25)) +
  labs(title = "Middle East & North Africa", subtitle = "Average Growth from Industry Transition by ISIC Sector",x="ISIC Industry Sector")
  

#Investigate Average Industry Segments driving growth in the "Information and Communication" ISIC Sector

#select only the industry category with the largest trending
MENA_Largest_Average <- MENA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
MENA_Largest_Average$growth_rate_variance <- MENA_Largest_Average$growth_rate_variance*100
MENA_Largest_Average$cumulative_growth_rate <- MENA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(MENA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:30)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 60), breaks=seq(0,60,5)) + 
  labs(title = "Middle East & North Africa: Information and communication", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth",x="Industry Segment Mean Variance") 

#visualize growth by industry section - bar chart
ggplot(MENA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-80, 60), breaks=seq(-80,60,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Middle East & North Africa: Information and communication", subtitle="Range of Growth from Industry Transition for the Information and communication Industry Segments", x="Information and Communication Industry Segments")

#visualize growth by industry section - box plot
ggplot(LAC_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-10, 12), breaks=seq(-10,12,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Middle East & North Africa: Information and communication", subtitle = "Growth from Industry Transition IQR for the Information and communication Industry Segments", x="Information and Communication Industry Segments")
```


```{r}
###  --- NORTH AMERICA: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
NA_EmployeeGrowth.df$isic_section_mean_rate <- NA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(NA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="AVerage Growth Rate 2015-2019 (%)", limits=c(0, 2.75), breaks=seq(0,2.75,.25)) +
  labs(title = "North America", subtitle = "Average Growth from Industry Transition by ISIC Sector", x="ISIC Industry Sector") 

#Investigate Average Industry Segments driving growth in the "Financial and Insurance activities" ISIC Sector

#select only the industry category with the largest trending
NA_Largest_Average <- NA_EmployeeData %>% filter(isic_section_name=="Financial and insurance activities")

#calculate raw values as percentages
NA_Largest_Average$growth_rate_variance <- NA_Largest_Average$growth_rate_variance*100
NA_Largest_Average$cumulative_growth_rate <- NA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(NA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=1) + 
  scale_x_continuous(breaks=-20:30)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 6), breaks=seq(0,6,2)) + 
  labs(title = "North America: Financial and insurance activities", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth",x="Industry Segment Mean Variance") 

#visualize growth by industry section - bar chart
ggplot(NA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-1, 20), breaks=seq(-1,20,10)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "North America: Financial and insurance activities",subtitle="Range of Growth from Industry Transition for the Financial and Insurace Industry Segments", x="Financial and Insurance Activities Industry Segments")

#visualize growth by industry section - box plot
ggplot(NA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(0, 10), breaks=seq(0,10,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "North America: Financial and insurance activities",subtitle="Growth from Industry Transition IQR for the Financial and Insurace Industry Segments", x="Financial and Insurance Activities Industry Segments")
```


```{r}
###  --- SOUTH ASIA: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
SA_EmployeeGrowth.df$isic_section_mean_rate <- SA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(SA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-2.0, 0), breaks=seq(-2.0,0,.25)) +
  labs(title = "South Asia", subtitle = "Average Growth from Industry Transition by ISIC Sector",x="ISIC Industry Sector") 

#Investigate Average Industry Segments driving growth in the "Information and Communications" ISIC Sector

#select only the industry category with the largest trending
SA_Largest_Average <- SA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
SA_Largest_Average$growth_rate_variance <- SA_Largest_Average$growth_rate_variance*100
SA_Largest_Average$cumulative_growth_rate <- SA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(SA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:20)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(0, 11), breaks=seq(0,11,1)) + 
  labs(title = "South Asia: Information and communication", subtitle = "Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth",x="Industry Segment Mean Variance") 
  
#visualize growth by industry section - bar chart
ggplot(SA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) +
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-28, 8), breaks=seq(-28,8,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "South Asia: Information and communication", subtitle = "Range of Growth from Industry Transition for the Information and Communication Industry Segments", x="Information and Communication Industry Segments")

#visualize growth by industry section - box plot
ggplot(SA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-8, 4), breaks=seq(-8,4,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "South Asia: Information and communication", subtitle = "Growth from Industry Transition IQR for the Information and Communication Industry Segments", x="Information and Communication Industry Segments")
```


```{r}
###  --- SUB SAHARAN AFRICA: VISUALIZING GROWTH FROM INDUSTRY TRANSITIONS ---  ###

#visualize Average Industry Growth for the 6 ISIC Sectors:

#convert to %
SSA_EmployeeGrowth.df$isic_section_mean_rate <- SSA_EmployeeGrowth.df$isic_section_mean_rate * 100

#visualize the trending
ggplot(SSA_EmployeeGrowth.df, aes(x=isic_section_name,y=isic_section_mean_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Average Growth Rate 2015-2019 (%)", limits=c(-1, 1), breaks=seq(-1,1,.25)) +
  labs(title = "Sub Saharan Africa", subtitle = "Average Growth from Industry Transition by ISIC Sector",x="ISIC Industry Sector") 

#Investigate Average Industry Segments driving growth in the "Information and Communications" ISIC Sector

#select only the industry category with the largest trending
SSA_Largest_Average <- SSA_EmployeeData %>% filter(isic_section_name=="Information and communication")

#calculate raw values as percentages
SSA_Largest_Average$growth_rate_variance <- SSA_Largest_Average$growth_rate_variance*100
SSA_Largest_Average$cumulative_growth_rate <- SSA_Largest_Average$cumulative_growth_rate*100

#plot percentages
ggplot(SSA_Largest_Average, aes(x=growth_rate_variance)) + 
  geom_histogram(color="blue", fill="white", binwidth=5) + 
  scale_x_continuous(breaks=-20:20)+ geom_vline(xintercept = 0, linetype="dotted", color = "red", size=1.5)  + 
  scale_y_continuous(name="Count", limits=c(-5, 20), breaks=seq(-5,20,10)) + 
  labs(title="Sub Saharan Africa: Information and communication", subtitle="Variance of Average Growth of Industry Segments from the ISIC Sector Average Growth",x="Industry Segment Mean Variance") 

#visualize growth by industry section - bar chart
ggplot(SSA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_bar(stat="identity", color="blue", fill="white") + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_y_continuous(name="AVerage Growth Rate 2015-2019 (%)", limits=c(-40, 15), breaks=seq(-40,15,5)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Sub Saharan Africa: Information and communication", subtitle = "Range of Growth from Industry Transition for the Information and Communication Industry Segments", x="Information and Communication Industry Segments")

#visualize growth by industry section - box plot
ggplot(SSA_Largest_Average, aes(x=industry_name,y=cumulative_growth_rate)) + 
  geom_boxplot(color="blue", fill="white") + 
  geom_hline(yintercept = 0, linetype="dotted", color = "red", size=1.5) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  scale_y_continuous(name="Cumulative Growth Rate 2015-2019 (%)", limits=c(-8, 8), breaks=seq(-8,8,2)) + 
  theme(axis.text.x = element_text(angle=90, vjust = 0.5, hjust=1)) + 
  labs(title = "Sub Saharan Africa: Information and communication", subtitle = "Growth from Industry Transition IQR for the Information and Communication Industry Segments", x="Information and Communication Industry Segments")
```



```{r}
#### PREPARE A NEW DATA FRAME WITH ONLY THE NUMERIC VALUES NEEDED FOR MODELING ####

#capture the data into a new data frame to hold only numeric values
  calculatedFieldsDF <- EmploymentGrowthDF
  
  ### START: High INCOME BINARY FIELD SET UP ###

    #1.) add a column to hold high income binary, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(high_income=0)
    
    #2.) find indexes of higher income countries
    highIncomeIndexList <- which(calculatedFieldsDF$wb_income=="High income")
    
    #3.) capture high income countries = 1
    calculatedFieldsDF$high_income[highIncomeIndexList] <- 1
    
    #4.) set field type to factor
    calculatedFieldsDF$high_income <- as.factor(calculatedFieldsDF$high_income)
    
  ### END: HIGH INCOME BINARY FIELD SET UP ###
  
  ### START: UPPER MIDDLE INCOME BINARY FIELD SET UP ###
    
    #1.) add a column to hold upper middle income classification, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(upper_middle_income=0)
    
    #2.) find indexes of middle income countries
    upperMiddleIncomeIndexList <- which(calculatedFieldsDF$wb_income=="Upper middle income")
    
    #3.) capture middle income countries = 1
    calculatedFieldsDF$upper_middle_income[upperMiddleIncomeIndexList] <- 1
  
    #4.) set field type to factor
    calculatedFieldsDF$upper_middle_income <- as.factor(calculatedFieldsDF$upper_middle_income)
    
  ### END: UPPER MIDDLE INCOME BINARY FIELD SET UP ###
    
  ### START: LOWER MIDDLE INCOME BINARY FIELD SET UP ###
    
    #1.) add a column to hold upper middle income classification, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(lower_middle_income=0)
    
    #2.) find indexes of middle income countries
    lowerMiddleIncomeIndexList <- which(calculatedFieldsDF$wb_income=="Lower middle income")
    
    #3.) capture middle income countries = 1
    calculatedFieldsDF$lower_middle_income[lowerMiddleIncomeIndexList] <- 1
  
    #4.) set field type to factor
    calculatedFieldsDF$lower_middle_income <- as.factor(calculatedFieldsDF$lower_middle_income)
    
  ### END: LOWER MIDDLE INCOME BINARY FIELD SET UP ###

  ### START: LOW INCOME BINARY FIELD SET UP ###
    
    #1.) add a column to hold upper middle income classification, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(low_income=0)
    
    #2.) find indexes of middle income countries
    lowIncomeIndexList <- which(calculatedFieldsDF$wb_income=="Low income")
    
    #3.) capture middle income countries = 1
    calculatedFieldsDF$low_income[lowIncomeIndexList] <- 1
  
    #4.) set field type to factor
    calculatedFieldsDF$low_income <- as.factor(calculatedFieldsDF$low_income)
    
  ### END: LOW INCOME BINARY FIELD SET UP ###
    
  ### START: BLENDED HIGHER INCOME BINARY FIELD SET UP ###
    
    #1.) add a column to hold blended upper income classification, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(blended_higher_income=0)
    
    #2.) capture middle income countries = 1
    calculatedFieldsDF$blended_higher_income[highIncomeIndexList] <- 1
    calculatedFieldsDF$blended_higher_income[upperMiddleIncomeIndexList] <- 1
  
    #4.) set field type to factor
    calculatedFieldsDF$blended_higher_income <- as.factor(calculatedFieldsDF$blended_higher_income)
    
  ### END: BLENDED HIGHER INCOME BINARY FIELD SET UP ###

  ### START: 2019 GROWTH CLASSIFICATION BINARY FIELD SET UP ###    
 
    #1.) add a column to hold binary growth classification for 2019, default to 0
    calculatedFieldsDF <- calculatedFieldsDF %>% mutate(growth_classification_2019=0)
  
    #2.) find indexes where 2019 growth is positive
    positiveGrowthIndexList <- which(calculatedFieldsDF$growth_rate_2019 > 0)
  
    #3.) capture 2019 growth classification = 1
    calculatedFieldsDF$growth_classification_2019[positiveGrowthIndexList] <- 1
  
    #4.) set new binary field as type factor
    calculatedFieldsDF$growth_classification_2019 <- as.factor(calculatedFieldsDF$growth_classification_2019)
    
  ### END: 2019 GROWTH CLASSIFICATION BINARY FIELD SET UP ### 
```

```{r}
#capture only the numeric variables in a new data frame
modelingDataFieldsDF <- data.frame(blended_higher_income=calculatedFieldsDF$blended_higher_income,
                                   high_income=calculatedFieldsDF$high_income,
                                   upper_middle_income=calculatedFieldsDF$upper_middle_income,
                                   lower_middle_income=calculatedFieldsDF$lower_middle_income,
                                   growth_classification_2019=calculatedFieldsDF$growth_classification_2019,
                                   growth_rate_2015=calculatedFieldsDF$growth_rate_2015,
                                   growth_rate_2016=calculatedFieldsDF$growth_rate_2016,
                                   growth_rate_2017=calculatedFieldsDF$growth_rate_2017,
                                   growth_rate_2018=calculatedFieldsDF$growth_rate_2018,
                                   growth_rate_2019=calculatedFieldsDF$growth_rate_2019,
                                   wb_region=calculatedFieldsDF$wb_region)

modelingDataFieldsDF$wb_region <- as.factor(modelingDataFieldsDF$wb_region)

#view the structure of the data frame
str(modelingDataFieldsDF)
```

```{r}
#view the correlation matrix for East Asia & Pacific
numericFieldsEAP <- modelingDataFieldsDF %>% filter(wb_region=="East Asia & Pacific")
cat("Correlation for Growth Rate for East Asia & Pacific: \n")
cor(numericFieldsEAP[6:10])

#view the correlation matrix for Europe & Central Asia
numericFieldsECA <- modelingDataFieldsDF %>% filter(wb_region=="Europe & Central Asia")
cat("\n Correlation for Growth Rate for Europe & Central Asia: \n")
cor(numericFieldsECA[6:10])

#view the correlation matrix for Latin America & Caribbean
numericFieldsLAC <- modelingDataFieldsDF %>% filter(wb_region=="Latin America & Caribbean")
cat("\n Correlation for Growth Rate for Latin America & Caribbean: \n")
cor(numericFieldsLAC[6:10])

cat("\n means:", mean(numericFieldsLAC$growth_rate_2015),mean(numericFieldsLAC$growth_rate_2016),mean(numericFieldsLAC$growth_rate_2017),mean(numericFieldsLAC$growth_rate_2018),mean(numericFieldsLAC$growth_rate_2019),"\n")

#view the correlation matrix for Middle East & North Africa
numericFieldsMENA <- modelingDataFieldsDF %>% filter(wb_region=="Middle East & North Africa")
cat("\n Correlation for Growth Rate for Middle East & North Africa: \n")
cor(numericFieldsMENA[6:10])

cat("\n means:", mean(numericFieldsMENA$growth_rate_2015),mean(numericFieldsMENA$growth_rate_2016),mean(numericFieldsMENA$growth_rate_2017),mean(numericFieldsMENA$growth_rate_2018),mean(numericFieldsMENA$growth_rate_2019),"\n")

#view the correlation matrix for North America
numericFieldsNA <- modelingDataFieldsDF %>% filter(wb_region=="North America")
cat("\n Correlation for Growth Rate for North America: \n")
cor(numericFieldsNA[6:10])

#view the correlation matrix for South Asia
numericFieldsSA <- modelingDataFieldsDF %>% filter(wb_region=="South Asia")
cat("\n Correlation for Growth Rate for South Asia: \n")
cor(numericFieldsSA[6:10])

cat("\n means:", mean(numericFieldsSA$growth_rate_2015),mean(numericFieldsSA$growth_rate_2016),mean(numericFieldsSA$growth_rate_2017),mean(numericFieldsSA$growth_rate_2018),mean(numericFieldsSA$growth_rate_2019),"\n")

#view the correlation matrix for Sub-Saharan Africa
numericFieldsSSA <- modelingDataFieldsDF %>% filter(wb_region=="Sub-Saharan Africa")
cat("\n Correlation for Growth Rate for Sub-Saharan Africa: \n")
cor(numericFieldsSSA[6:10])
```


```{r}
### LINEAR MODELING: PREDICT 2019 #### 

  #perform the linear regression model using the numeric-only data set
  linear.Model.1 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsEAP)

  #output the summary of the linear model
  cat("*** East Asia & Pacific: *** \n")
  summary(linear.Model.1)
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.2 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsECA)

  #output the summary of the linear model
  cat("*** Europe & Central Asia: *** \n")
  summary(linear.Model.2)
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.3 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsLAC)

  #output the summary of the linear model
  cat("*** Latin America & Caribbean: *** \n")  
  summary(linear.Model.3)
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.4 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsMENA)

  #output the summary of the linear model
  cat("*** Middle East & North Africa: *** \n")    
  summary(linear.Model.4)  
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.5 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsNA)

  #output the summary of the linear model
  cat("*** North America: *** \n") 
  summary(linear.Model.5)  
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.6 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsSA)

  #output the summary of the linear model
  cat("*** South Asia: *** \n") 
  summary(linear.Model.6)  
  
  #perform the linear regression model using the numeric-only data set
  linear.Model.7 <-lm(growth_rate_2019~growth_rate_2015+growth_rate_2016+growth_rate_2017+growth_rate_2018, data = numericFieldsSSA)

  #output the summary of the linear model
  cat("*** Sub-Saharan Africa: *** \n") 
  summary(linear.Model.7)  
```

```{r}
#make the sampling predictable by setting the seed value
set.seed(1000)

#select 70% training data and store indexes
trainList <- createDataPartition(y=modelingDataFieldsDF$blended_higher_income,p=0.70,list=FALSE)

#include all of the elements at the indices in the training data set
trainingDataSet <- modelingDataFieldsDF[trainList,]

#construct the test set from everything that didn't go into training
testingDataSet <- modelingDataFieldsDF[-trainList,]

#train the model
svm.model.blendedHigherIncome <- train(blended_higher_income~.,
                   data=trainingDataSet,method="svmRadial",
                   trControl=trainControl(method="none"),
                   preProc=c("center","scale"))

#output the final model summary
svm.model.blendedHigherIncome$finalModel

```
```{r}
#Assess fit of the model with the test data
svmPrediction <- predict(svm.model.blendedHigherIncome, testingDataSet, type="raw")

#build a confusion matrix with caret package function
confusionMatrix <- confusionMatrix(svmPrediction,testingDataSet$blended_higher_income)

confusionMatrix
```

```{r}
#build the model
model.rpart.blendedHigherIncome <- rpart(blended_higher_income~.,data=trainingDataSet,method="class")

#visualize the results using rpart.plot()
rpart.plot(model.rpart.blendedHigherIncome)
```

```{r}
#make predictions on the test set
predictions <- predict(model.rpart.blendedHigherIncome, testingDataSet, type="class")

#output results in table format
table(testingDataSet$blended_higher_income,predictions)
```



```{r}
#make the sampling predictable by setting the seed value
set.seed(1000)

#select 70% training data and store indexes
trainList2 <- createDataPartition(y=modelingDataFieldsDF$growth_classification_2019, p=0.70,list=FALSE)

#include all of the elements at the indices in the training data set
trainingDataSet2 <- modelingDataFieldsDF[trainList2,]

#construct the test set from everything that didn't go into training
testingDataSet2 <- modelingDataFieldsDF[-trainList2,]

#train the model
svm.model.2019Growth <- train(growth_classification_2019~.,
                   data=trainingDataSet2,method="svmRadial",
                   trControl=trainControl(method="none"),
                   preProc=c("center","scale"))

#output the final model summary
svm.model.2019Growth$finalModel

```

```{r}
#Assess fit of the model with the test data
svmPrediction2 <- predict(svm.model.2019Growth, testingDataSet2, type="raw")

#build a confusion matrix with caret package function
confusionMatrix <- confusionMatrix(svmPrediction2,testingDataSet2$growth_classification_2019)

confusionMatrix
```


```{r}
#build the model
model.rpart.2019GrowthClassification <- rpart(growth_classification_2019~.,data=trainingDataSet,method="class")

#visualize the results using rpart.plot()
rpart.plot(model.rpart.2019GrowthClassification)
```


```{r}
#make predictions on the test set
predictions2 <- predict(model.rpart.2019GrowthClassification, testingDataSet, type="class")

#output results in table format
table(testingDataSet$growth_classification_2019,predictions2)
```